AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Kiosk Screen Capture

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    Runtime: nodejs14.x
    CodeUri: dist/ # it could be an S3 bucket location (.zip)
#    DeadLetterQueue:
#    Description:
    MemorySize: 128
#    Environment:
#    Tags:
#    Tracing:

#Api:
##  # Properties of AWS::Serverless::Api
##  # Also works with Implicit APIs
##  Auth:
##  Name:
##  DefinitionUri:
##  EndpointConfiguration:
##  MethodSettings:
#  Cors:
#    AllowMethods: "'GET,POST,DELETE'"
#    AllowHeaders: "'X-Forwarded-For'"
##    AllowOrigin: "*.my-domain.com"
##  GatewayResponses:
##  TracingEnabled:
##  OpenApiVersion:
#  MinimumCompressionSize: 1024

Resources:
  KioskScreenCapture:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: KioskScreenCapture
      Description: Kiosk Screen Capture
#      Timeout: 30
#      Runtime: nodejs14.x
#      CodeUri: .
      Timeout: 3
#      Role: 'arn:aws:iam::305370495358:role/service-role/short-id-role-5v4x97td'
      Handler: src/screenCapture/function.lambdaHandler
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /screencapture
            Method: GET
#      Events:
#        HelloWorld:
#          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
#          Properties:
#            Path: /api/v1/hello
#            Method: get

#Outputs:
#  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
#  # Find out more about other implicit resources you can reference within SAM
#  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
#  HelloWorldApi:
#    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
#    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
#  HelloWorldFunction:
#    Description: "Hello World Lambda Function ARN"
#    Value: !GetAtt HelloWorldFunction.Arn
#  HelloWorldFunctionIamRole:
#    Description: "Implicit IAM Role created for Hello World function"
#    Value: !GetAtt HelloWorldFunctionRole.Arn

#AWSTemplateFormatVersion: '2010-09-09'
#Transform: 'AWS::Serverless-2016-10-31'
#Description: An AWS Serverless Specification template describing your function.
#Resources:
#  shortid:
#    Type: 'AWS::Serverless::Function'
#    Properties:
#      Handler: index.handler
#      Runtime: nodejs10.x
#      CodeUri: .
#      Description: ''
#      MemorySize: 128
#      Timeout: 3
#      Role: 'arn:aws:iam::305370495358:role/service-role/short-id-role-5v4x97td'
#      Events:
#        Api1:
#          Type: Api
#          Properties:
#            Path: /screencapture
#            Method: GET
#        Api2:
#          Type: Api
#          Properties:
#            Path: /MyResource
#            Method: ANY
