AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Kiosk Lambda

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    Runtime: nodejs14.x
    CodeUri: dist/ # it could be an S3 bucket location (.zip)
    MemorySize: 128
  Api:
    EndpointConfiguration: EDGE

#####
# MANUAL
#  Associated API Stages
#  add IoT permission
#  add S3
####
Resources:
  screenCapture:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: screenCapture
      Description: Kiosk screen capture
      Timeout: 30
      #      Role: 'arn:aws:iam::305370495358:role/service-role/short-id-role-5v4x97td'
      Handler: screenCapture/function.lambdaHandler
      Events:
        Api:
          Type: Api
          Properties:
            Path: /screen-capture
            Method: POST
            Auth:
              ApiKeyRequired: true # OPTIONAL
              UsagePlan: # OPTIONAL
                CreateUsagePlan: PER_API # REQUIRED if UsagePlan property is set. accepted values: PER_API, SHARED, NONE
  loadURL:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: loadURL
      Description: Kiosk load URL
      Timeout: 3
#      Role: 'arn:aws:iam::305370495358:role/service-role/short-id-role-5v4x97td'
      Handler: loadURL/function.lambdaHandler
      Events:
        Api:
          Type: Api
          Properties:
            Path: /loadURL
            Method: POST
            Auth:
              ApiKeyRequired: true # OPTIONAL
              UsagePlan: # OPTIONAL
                CreateUsagePlan: PER_API # REQUIRED if UsagePlan property is set. accepted values: PER_API, SHARED, NONE