name: mir-kiosk-electron
version: '0.1'
summary: mir-kiosk electron
description: |
  mir-kiosk electron
base: core18
confinement: strict
grade: devel
compression: lzo

apps:
  mir-kiosk-electron:
    daemon: simple
    stop-timeout: 1m
    extensions: [ gnome-3-28 ]
    restart-condition: always
    command: snap/command-chain/desktop-launch xwayland-kiosk-launch electron.launcher
    plugs:
      - browser-support
      - network
      - network-bind
      - opengl
      - pulseaudio
      - wayland

layout:
  /usr/share/fonts:
    bind: $SNAP/usr/share/fonts

environment:
  XWAYLAND_FULLSCREEN_WINDOW_HINT: window_role="browser-window"

parts:
  mir-kiosk-electron:
    plugin: nil
    after: [ certs ]
    source: https://github.com/zhex900/mir-kiosk-electron.git
    override-build: |
      cd electron-kiosk
      cp -r snap snap_copy
      rm -rf snap 
      cp -r snap_copy/* .
      chmod +x glue/electron.launcher
      npm config set scripts-prepend-node-path true
      npm install --unsafe-perm=true
      npm run package
      ls
      cp -R ./out/mir-kiosk-electron-linux-* $SNAPCRAFT_PART_INSTALL/mir-kiosk-electron
      cp -r /root/stage/certs $SNAPCRAFT_PART_INSTALL/mir-kiosk-electron/certs
    stage-packages:
      - libnspr4
      - libnss3
    build-snaps:
      - node/14/stable

  xwayland-kiosk-helper:
    plugin: cmake
    source: https://github.com/MirServer/xwayland-kiosk-helper.git
    build-packages: [ build-essential ]
    stage-packages: [ xwayland, i3, libegl1-mesa, libgl1-mesa-glx ]

  certs: 
    plugin: dump
    source: certs
    organize:
      certificate.pem: certs/
      private.key: certs/

  launcher:
    plugin: dump
    source: glue
    after: [ mir-kiosk-electron, xwayland-kiosk-helper ]
    organize:
      electron.launcher: bin/